/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminListingsListingIdRouteImport } from './routes/admin/listings/$listingId'
import { Route as AdminListingsNewRouteImport } from './routes/admin/listings/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsListingIdRoute = AdminListingsListingIdRouteImport.update({
  id: '/admin/listings/$listingId',
  path: '/admin/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/admin/listings/new',
  path: '/admin/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/admin/'
    | '/admin/listings/$listingId'
    | '/admin/listings/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin'
    | '/admin/listings/$listingId'
    | '/admin/listings/new'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/admin/'
    | '/admin/listings/$listingId'
    | '/admin/listings/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminListingsListingIdRoute: typeof AdminListingsListingIdRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/$listingId': {
      id: '/admin/listings/$listingId'
      path: '/admin/listings/$listingId'
      fullPath: '/admin/listings/$listingId'
      preLoaderRoute: typeof AdminListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/admin/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminListingsListingIdRoute: AdminListingsListingIdRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
